defaults:
  project_id: "{{cookiecutter._internal_vars.default_project}}"
  region: "{{cookiecutter._internal_vars.region}}"
  pipeline_root: "gs://{{cookiecutter._internal_vars.default_project}}-vertex-ai/pipeline_root"
  aliz_aip_project: "{{cookiecutter._internal_vars.aliz_aip_project}}"
  service_account: "{{cookiecutter.name}}-sa@{{cookiecutter._internal_vars.default_project}}.iam.gserviceaccount.com"
pipelines:
  - source: "pipelines.training.pipeline"
    base_image: "{{cookiecutter.zone|gcr_location|lower}}.gcr.io/{{cookiecutter._internal_vars.default_project}}/project-base:latest_train"
    run_schedule: "0 0 * * *"
    pipeline_arguments: null
    project_name: "{{cookiecutter._internal_vars.default_project}}"
  - source: "pipelines.batch_prediction.batch_prediction_vtx"
    base_image: "{{cookiecutter.zone|gcr_location|lower}}.gcr.io/{{cookiecutter._internal_vars.default_project}}/project-base:latest_pred"
    run_schedule: "0 0 * * *"
    pipeline_arguments: null
    project_name: "{{cookiecutter._internal_vars.default_project}}"
